
[general]
	#Show current player coordinates on the death screen.
	"Death Screen Coordinates" = false
	#Give the player an explorer map on respawn leading to their point of death.
	"Death Maps" = false
	#Add coordinates to the end of ever death message.
	"Death Message Coordinates" = true

[death_messages]
	#Show death message for named entities.
	"Named Entity Deaths" = true
	#Entities to be excluded when "All Deaths" is enabled. Format for every entry is "<namespace>:<id>".
	"Entity Blacklist" = ["minecraft:bat"]
	#Only entities to be included when "All Deaths" is enabled. Format for every entry is "<namespace>:<id>".
	"Entity Whitelist" = []
	#Show death message for tamed entities.
	"Pet Deaths" = true
	#Show death message for player entities.
	"Player Deaths" = true
	#Show death message for all entities.
	"All Deaths" = false

[death_maps]
	#Icon to mark a death point with.
	#Allowed Values: PLAYER, FRAME, RED_MARKER, BLUE_MARKER, TARGET_X, TARGET_POINT, PLAYER_OFF_MAP, PLAYER_OFF_LIMITS, MANSION, MONUMENT, BANNER_WHITE, BANNER_ORANGE, BANNER_MAGENTA, BANNER_LIGHT_BLUE, BANNER_YELLOW, BANNER_LIME, BANNER_PINK, BANNER_GRAY, BANNER_LIGHT_GRAY, BANNER_CYAN, BANNER_PURPLE, BANNER_BLUE, BANNER_BROWN, BANNER_GREEN, BANNER_RED, BANNER_BLACK, RED_X
	"Death Marker" = "TARGET_X"
	#Give maps even when the "keepInventory" gamerule is enabled.
	"Ignore Keep Inventory" = true

